swagger: '2.0'
info:
  description: 'This REST API service provides an interface to serve Angular 6 website.'
  version: 1.1.0
  title: ArcGIS Heatmap Example  
host: localhost:3000
basePath: "/api/arcgis/v1"
tags:
  - name: Heatmap
    description: Get Heatmap.
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
securityDefinitions:
  bearer:
    type: apiKey
    name: Authorization
    in: header
paths:
  $ref: './paths/paths.yaml'
definitions:
  $ref: './definitions/definitions.yaml'
